DROP TABLE Incidencia CASCADE CONSTRAINTS PURGE;
DROP TABLE Compra CASCADE CONSTRAINTS PURGE;
DROP TABLE Funcion CASCADE CONSTRAINTS PURGE;
DROP TABLE Butaca CASCADE CONSTRAINTS PURGE;
DROP TABLE Sala CASCADE CONSTRAINTS PURGE;
DROP TABLE Calificacion CASCADE CONSTRAINTS PURGE;
DROP TABLE Cliente CASCADE CONSTRAINTS PURGE;
DROP TABLE Promocion CASCADE CONSTRAINTS PURGE;
DROP TABLE Pelicula CASCADE CONSTRAINTS PURGE;
DROP TABLE Producto CASCADE CONSTRAINTS PURGE;

CREATE TABLE Pelicula (
    id_pelicula NUMBER(10) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    titulo VARCHAR2(255) NOT NULL,
    duracion_minutos NUMBER(10) NOT NULL,
    genero VARCHAR2(100),
    sinopsis CLOB,
    imagen_url VARCHAR2(500),
    destacado NUMBER(1) DEFAULT 0
);

CREATE TABLE Cliente (
    id_cliente NUMBER(10) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    dni VARCHAR2(20) NOT NULL UNIQUE,
    nombre VARCHAR2(255) NOT NULL,
    email VARCHAR2(255),
    telefono VARCHAR2(20)
);

CREATE TABLE Promocion (
    id_promocion NUMBER(10) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo VARCHAR2(20) NOT NULL UNIQUE,
    descripcion VARCHAR2(200),
    descuento NUMBER(3) NOT NULL,
    activo NUMBER(1) DEFAULT 1
);

CREATE TABLE Calificacion (
    id_cliente NUMBER(10) NOT NULL,
    id_pelicula NUMBER(10) NOT NULL,
    puntuacion NUMBER(3) NOT NULL CHECK (puntuacion BETWEEN 1 AND 5),
    comentario CLOB,
    fecha_calificacion TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id_cliente, id_pelicula),
    FOREIGN KEY (id_cliente) REFERENCES Cliente(id_cliente) ON DELETE CASCADE,
    FOREIGN KEY (id_pelicula) REFERENCES Pelicula(id_pelicula) ON DELETE CASCADE
);

CREATE TABLE Sala (
    id_sala NUMBER(10) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR2(100) NOT NULL UNIQUE,
    tipo VARCHAR2(20) NOT NULL,
    capacidad_total NUMBER(10) NOT NULL
);

CREATE TABLE Butaca (
    id_butaca NUMBER(10) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_sala NUMBER(10) NOT NULL,
    fila VARCHAR2(5) NOT NULL,
    numero NUMBER(10) NOT NULL,
    estado VARCHAR2(20) DEFAULT 'Disponible' NOT NULL CHECK (estado IN ('Disponible', 'Seleccionada', 'Vendida', 'Mantenimiento')),
    FOREIGN KEY (id_sala) REFERENCES Sala(id_sala) ON DELETE CASCADE,
    UNIQUE (id_sala, fila, numero)
);

CREATE TABLE Funcion (
    id_funcion NUMBER(10) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_pelicula NUMBER(10) NOT NULL,
    id_sala NUMBER(10) NOT NULL,
    hora_inicio TIMESTAMP NOT NULL,
    estado VARCHAR2(20) DEFAULT 'Programada' NOT NULL CHECK (estado IN ('Programada', 'En curso', 'Finalizada', 'Cancelada')),
    FOREIGN KEY (id_pelicula) REFERENCES Pelicula(id_pelicula) ON DELETE CASCADE,
    FOREIGN KEY (id_sala) REFERENCES Sala(id_sala) ON DELETE CASCADE
);

CREATE TABLE Producto (
    id_producto NUMBER(10) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR2(100) NOT NULL,
    descripcion VARCHAR2(255),
    precio NUMBER(10,2) NOT NULL,
    imagen_url VARCHAR2(500),
    categoria VARCHAR2(50) DEFAULT 'Comida' CHECK (categoria IN ('Comida', 'Bebida', 'Combo')),
    activo NUMBER(1) DEFAULT 1
);

CREATE TABLE Compra (
    id_compra NUMBER(10) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_cliente NUMBER(10) NOT NULL,
    id_funcion NUMBER(10) NOT NULL,
    id_butaca NUMBER(10) NOT NULL,
    precio NUMBER(10,2) NOT NULL,
    metodo_pago VARCHAR2(50) NOT NULL CHECK (metodo_pago IN ('Efectivo', 'Tarjeta Visa', 'Tarjeta Mastercard', 'Yape', 'Plin')),
    estado VARCHAR2(20) NOT NULL,
    codigo_qr VARCHAR2(500) UNIQUE,
    fecha_compra TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    productos VARCHAR2(500),
    FOREIGN KEY (id_cliente) REFERENCES Cliente(id_cliente) ON DELETE CASCADE,
    FOREIGN KEY (id_funcion) REFERENCES Funcion(id_funcion) ON DELETE CASCADE,
    FOREIGN KEY (id_butaca) REFERENCES Butaca(id_butaca) ON DELETE CASCADE
);

CREATE TABLE Incidencia (
    id_incidencia NUMBER(10) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tipo VARCHAR2(100) NOT NULL CHECK (tipo IN ('Error en QR', 'Conflicto de asientos', 'Fallo tecnico')),
    descripcion VARCHAR2(500),
    id_sala NUMBER(10),
    id_funcion NUMBER(10),
    id_cliente NUMBER(10),
    fecha_reporte TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    estado VARCHAR2(50),
    FOREIGN KEY (id_sala) REFERENCES Sala(id_sala) ON DELETE SET NULL,
    FOREIGN KEY (id_funcion) REFERENCES Funcion(id_funcion) ON DELETE SET NULL,
    FOREIGN KEY (id_cliente) REFERENCES Cliente(id_cliente) ON DELETE SET NULL
);

COMMIT;
