CREATE TABLE Producto (
    id_producto NUMBER(10) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR2(100) NOT NULL,
    descripcion VARCHAR2(255),
    precio NUMBER(10,2) NOT NULL,
    imagen_url VARCHAR2(500),
    categoria VARCHAR2(50) DEFAULT 'Comida' CHECK (categoria IN ('Comida', 'Bebida', 'Combo')),
    activo NUMBER(1) DEFAULT 1
);

ALTER TABLE Compra ADD (productos VARCHAR2(500));

DROP TABLE Compra_Producto CASCADE CONSTRAINTS PURGE;

COMMIT;
