-- Full reset: drops tables, recreates, inserts seed data (IDs start at 1)

DROP TABLE Incidencia CASCADE CONSTRAINTS PURGE;
DROP TABLE Compra CASCADE CONSTRAINTS PURGE;
DROP TABLE Funcion CASCADE CONSTRAINTS PURGE;
DROP TABLE Butaca CASCADE CONSTRAINTS PURGE;
DROP TABLE Sala CASCADE CONSTRAINTS PURGE;
DROP TABLE Calificacion CASCADE CONSTRAINTS PURGE;
DROP TABLE Cliente CASCADE CONSTRAINTS PURGE;
DROP TABLE Promocion CASCADE CONSTRAINTS PURGE;
DROP TABLE Pelicula CASCADE CONSTRAINTS PURGE;
DROP TABLE Producto CASCADE CONSTRAINTS PURGE;

CREATE TABLE Pelicula (
    id_pelicula NUMBER(10) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    titulo VARCHAR2(255) NOT NULL,
    duracion_minutos NUMBER(10) NOT NULL,
    genero VARCHAR2(100),
    sinopsis CLOB,
    imagen_url VARCHAR2(500),
    destacado NUMBER(1) DEFAULT 0
);

CREATE TABLE Cliente (
    id_cliente NUMBER(10) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    dni VARCHAR2(20) NOT NULL UNIQUE,
    nombre VARCHAR2(255) NOT NULL,
    email VARCHAR2(255),
    telefono VARCHAR2(20)
);

CREATE TABLE Promocion (
    id_promocion NUMBER(10) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo VARCHAR2(20) NOT NULL UNIQUE,
    descripcion VARCHAR2(200),
    descuento NUMBER(3) NOT NULL,
    activo NUMBER(1) DEFAULT 1
);

INSERT INTO Promocion (codigo, descripcion, descuento) VALUES ('ESTUDIANTE30','Descuento estudiante',30);
INSERT INTO Promocion (codigo, descripcion, descuento) VALUES ('MARTES2X1','Martes de cine 2x1',50);
INSERT INTO Promocion (codigo, descripcion, descuento) VALUES ('COMBO20','Combo familiar 20%',20);
INSERT INTO Promocion (codigo, descripcion, descuento) VALUES ('SANVALENTIN','San Valentin 2x1',50);

CREATE TABLE Calificacion (
    id_cliente NUMBER(10) NOT NULL,
    id_pelicula NUMBER(10) NOT NULL,
    puntuacion NUMBER(3) NOT NULL CHECK (puntuacion BETWEEN 1 AND 5),
    comentario CLOB,
    fecha_calificacion TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id_cliente, id_pelicula),
    FOREIGN KEY (id_cliente) REFERENCES Cliente(id_cliente) ON DELETE CASCADE,
    FOREIGN KEY (id_pelicula) REFERENCES Pelicula(id_pelicula) ON DELETE CASCADE
);

CREATE TABLE Sala (
    id_sala NUMBER(10) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR2(100) NOT NULL UNIQUE,
    tipo VARCHAR2(20) NOT NULL,
    capacidad_total NUMBER(10) NOT NULL
);

CREATE TABLE Butaca (
    id_butaca NUMBER(10) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_sala NUMBER(10) NOT NULL,
    fila VARCHAR2(5) NOT NULL,
    numero NUMBER(10) NOT NULL,
    estado VARCHAR2(20) DEFAULT 'Disponible' NOT NULL CHECK (estado IN ('Disponible', 'Seleccionada', 'Vendida', 'Mantenimiento')),
    FOREIGN KEY (id_sala) REFERENCES Sala(id_sala) ON DELETE CASCADE,
    UNIQUE (id_sala, fila, numero)
);

CREATE TABLE Funcion (
    id_funcion NUMBER(10) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_pelicula NUMBER(10) NOT NULL,
    id_sala NUMBER(10) NOT NULL,
    hora_inicio TIMESTAMP NOT NULL,
    estado VARCHAR2(20) DEFAULT 'Programada' NOT NULL CHECK (estado IN ('Programada', 'En curso', 'Finalizada', 'Cancelada')),
    FOREIGN KEY (id_pelicula) REFERENCES Pelicula(id_pelicula) ON DELETE CASCADE,
    FOREIGN KEY (id_sala) REFERENCES Sala(id_sala) ON DELETE CASCADE
);

CREATE TABLE Producto (
    id_producto NUMBER(10) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR2(100) NOT NULL,
    descripcion VARCHAR2(255),
    precio NUMBER(10,2) NOT NULL,
    imagen_url VARCHAR2(500),
    categoria VARCHAR2(50) DEFAULT 'Comida' CHECK (categoria IN ('Comida', 'Bebida', 'Combo')),
    activo NUMBER(1) DEFAULT 1
);

CREATE TABLE Compra (
    id_compra NUMBER(10) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_cliente NUMBER(10) NOT NULL,
    id_funcion NUMBER(10) NOT NULL,
    id_butaca NUMBER(10) NOT NULL,
    precio NUMBER(10,2) NOT NULL,
    metodo_pago VARCHAR2(50) NOT NULL CHECK (metodo_pago IN ('Efectivo', 'Tarjeta Visa', 'Tarjeta Mastercard', 'Yape', 'Plin')),
    estado VARCHAR2(20) NOT NULL,
    codigo_qr VARCHAR2(500) UNIQUE,
    fecha_compra TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    productos VARCHAR2(500),
    FOREIGN KEY (id_cliente) REFERENCES Cliente(id_cliente) ON DELETE CASCADE,
    FOREIGN KEY (id_funcion) REFERENCES Funcion(id_funcion) ON DELETE CASCADE,
    FOREIGN KEY (id_butaca) REFERENCES Butaca(id_butaca) ON DELETE CASCADE
);

CREATE TABLE Incidencia (
    id_incidencia NUMBER(10) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tipo VARCHAR2(100) NOT NULL CHECK (tipo IN ('Error en QR', 'Conflicto de asientos', 'Fallo tecnico')),
    descripcion VARCHAR2(500),
    id_sala NUMBER(10),
    id_funcion NUMBER(10),
    id_cliente NUMBER(10),
    fecha_reporte TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    estado VARCHAR2(50),
    FOREIGN KEY (id_sala) REFERENCES Sala(id_sala) ON DELETE SET NULL,
    FOREIGN KEY (id_funcion) REFERENCES Funcion(id_funcion) ON DELETE SET NULL,
    FOREIGN KEY (id_cliente) REFERENCES Cliente(id_cliente) ON DELETE SET NULL
);

-- ==================== SEED DATA ====================
-- All IDs auto-generated by identity columns (starting from 1)

-- Peliculas → IDs 1..5
INSERT INTO Pelicula (titulo, duracion_minutos, genero, sinopsis) VALUES ('El Padrino', 175, 'Drama', 'La historia de la familia mafiosa Corleone.');
INSERT INTO Pelicula (titulo, duracion_minutos, genero, sinopsis) VALUES ('Interestelar', 169, 'Ciencia Ficcion', 'Un viaje interestelar para salvar la humanidad.');
INSERT INTO Pelicula (titulo, duracion_minutos, genero, sinopsis) VALUES ('El Senor de los Anillos', 201, 'Fantasia', 'La busqueda del anillo unico.');
INSERT INTO Pelicula (titulo, duracion_minutos, genero, sinopsis) VALUES ('Toy Story', 81, 'Animacion', 'Los juguetes cobran vida.');
INSERT INTO Pelicula (titulo, duracion_minutos, genero, sinopsis) VALUES ('Parasitos', 132, 'Suspenso', 'Una familia pobre se infiltra en una familia rica.');

-- Clientes → IDs 1..3 (admin=1, Carlos=2, Maria=3)
INSERT INTO Cliente (dni, nombre, email, telefono) VALUES ('00000000', 'admin', 'admin@cinerama.com', '999000000');
INSERT INTO Cliente (dni, nombre, email, telefono) VALUES ('12345678', 'Carlos Perez', 'carlos@email.com', '987654321');
INSERT INTO Cliente (dni, nombre, email, telefono) VALUES ('87654321', 'Maria Gomez', 'maria@email.com', '987654322');

-- Salas → IDs 1..4 (Premium=1, Principal=2, 3D=3, IMAX=4)
INSERT INTO Sala (nombre, tipo, capacidad_total) VALUES ('Sala Premium', 'vip', 30);
INSERT INTO Sala (nombre, tipo, capacidad_total) VALUES ('Sala Principal', '2d', 80);
INSERT INTO Sala (nombre, tipo, capacidad_total) VALUES ('Sala 3D', '3d', 60);
INSERT INTO Sala (nombre, tipo, capacidad_total) VALUES ('Sala IMAX', 'imax', 50);

-- Butacas via PL/SQL (IDs auto-generated 1..220)
BEGIN
  -- Sala 1 (Premium): 30 butacas, filas A-C x 10
  FOR i IN 1..10 LOOP INSERT INTO Butaca (id_sala, fila, numero, estado) VALUES (1, 'A', i, 'Disponible'); END LOOP;
  FOR i IN 1..10 LOOP INSERT INTO Butaca (id_sala, fila, numero, estado) VALUES (1, 'B', i, 'Disponible'); END LOOP;
  FOR i IN 1..10 LOOP INSERT INTO Butaca (id_sala, fila, numero, estado) VALUES (1, 'C', i, 'Disponible'); END LOOP;

  -- Sala 2 (Principal): 80 butacas, filas A-H x 10
  FOR i IN 1..10 LOOP INSERT INTO Butaca (id_sala, fila, numero, estado) VALUES (2, 'A', i, 'Disponible'); END LOOP;
  FOR i IN 1..10 LOOP INSERT INTO Butaca (id_sala, fila, numero, estado) VALUES (2, 'B', i, 'Disponible'); END LOOP;
  FOR i IN 1..10 LOOP INSERT INTO Butaca (id_sala, fila, numero, estado) VALUES (2, 'C', i, 'Disponible'); END LOOP;
  FOR i IN 1..10 LOOP INSERT INTO Butaca (id_sala, fila, numero, estado) VALUES (2, 'D', i, 'Disponible'); END LOOP;
  FOR i IN 1..10 LOOP INSERT INTO Butaca (id_sala, fila, numero, estado) VALUES (2, 'E', i, 'Disponible'); END LOOP;
  FOR i IN 1..10 LOOP INSERT INTO Butaca (id_sala, fila, numero, estado) VALUES (2, 'F', i, 'Disponible'); END LOOP;
  FOR i IN 1..10 LOOP INSERT INTO Butaca (id_sala, fila, numero, estado) VALUES (2, 'G', i, 'Disponible'); END LOOP;
  FOR i IN 1..10 LOOP INSERT INTO Butaca (id_sala, fila, numero, estado) VALUES (2, 'H', i, 'Disponible'); END LOOP;

  -- Sala 3 (3D): 60 butacas, filas A-F x 10
  FOR i IN 1..10 LOOP INSERT INTO Butaca (id_sala, fila, numero, estado) VALUES (3, 'A', i, 'Disponible'); END LOOP;
  FOR i IN 1..10 LOOP INSERT INTO Butaca (id_sala, fila, numero, estado) VALUES (3, 'B', i, 'Disponible'); END LOOP;
  FOR i IN 1..10 LOOP INSERT INTO Butaca (id_sala, fila, numero, estado) VALUES (3, 'C', i, 'Disponible'); END LOOP;
  FOR i IN 1..10 LOOP INSERT INTO Butaca (id_sala, fila, numero, estado) VALUES (3, 'D', i, 'Disponible'); END LOOP;
  FOR i IN 1..10 LOOP INSERT INTO Butaca (id_sala, fila, numero, estado) VALUES (3, 'E', i, 'Disponible'); END LOOP;
  FOR i IN 1..10 LOOP INSERT INTO Butaca (id_sala, fila, numero, estado) VALUES (3, 'F', i, 'Disponible'); END LOOP;

  -- Sala 4 (IMAX): 50 butacas, filas A-E x 10
  FOR i IN 1..10 LOOP INSERT INTO Butaca (id_sala, fila, numero, estado) VALUES (4, 'A', i, 'Disponible'); END LOOP;
  FOR i IN 1..10 LOOP INSERT INTO Butaca (id_sala, fila, numero, estado) VALUES (4, 'B', i, 'Disponible'); END LOOP;
  FOR i IN 1..10 LOOP INSERT INTO Butaca (id_sala, fila, numero, estado) VALUES (4, 'C', i, 'Disponible'); END LOOP;
  FOR i IN 1..10 LOOP INSERT INTO Butaca (id_sala, fila, numero, estado) VALUES (4, 'D', i, 'Disponible'); END LOOP;
  FOR i IN 1..10 LOOP INSERT INTO Butaca (id_sala, fila, numero, estado) VALUES (4, 'E', i, 'Disponible'); END LOOP;
END;
/

-- Productos → IDs 1..6
INSERT INTO Producto (nombre, descripcion, precio, categoria, activo) VALUES ('Cancha Grande', 'Cancha de maiz gigante', 12.00, 'Comida', 1);
INSERT INTO Producto (nombre, descripcion, precio, categoria, activo) VALUES ('Cancha Chica', 'Cancha de maiz pequeña', 8.00, 'Comida', 1);
INSERT INTO Producto (nombre, descripcion, precio, categoria, activo) VALUES ('Gaseosa 1L', 'Gaseosa de 1 litro', 10.00, 'Bebida', 1);
INSERT INTO Producto (nombre, descripcion, precio, categoria, activo) VALUES ('Agua 500ml', 'Agua mineral', 5.00, 'Bebida', 1);
INSERT INTO Producto (nombre, descripcion, precio, categoria, activo) VALUES ('Combo Duo', '2 canchas + 2 gaseosas', 30.00, 'Combo', 1);
INSERT INTO Producto (nombre, descripcion, precio, categoria, activo) VALUES ('Combo Personal', '1 cancha + 1 gaseosa', 18.00, 'Combo', 1);

-- Funcion (ID 1): El Padrino (id=1) en Sala Premium (id=1), 2026-06-17 22:10
INSERT INTO Funcion (id_pelicula, id_sala, hora_inicio, estado) VALUES (1, 1, TO_TIMESTAMP('2026-06-17 22:10', 'YYYY-MM-DD HH24:MI'), 'Programada');

COMMIT;
EXIT;
